.env:
  directory: "../secrets/"
  filename: "info.env"

server:
  port: 5000
#  ssl:
#    enabled: true
#    key-store: keystore.p12
#    key-store-password: elwlahs21@
#    key-store-type: PKCS12
#    key-alias: bns-ssl
#    tomcat:
#      threads:
#        max: 512
#    servlet:
#      context-path: /
#      encoding:
#        charset: UTF-8
#        enabled: true
#        force: true
#      session:
#        cookie:
#          secure: false

spring:
  application:
    name: bookhub-service

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hikari:
      minimum-idle: 50
      maximum-pool-size: 50

#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console

#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    #;DB_CLOSE_DELAY=-1
#    #    url: jdbc:h2:tcp://localhost:8200/testdb
#    username: sa
#    password:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rds-mysql-dev-uplus-bookhub-instance-0.c2cxsnsaan5b.ap-northeast-2.rds.amazonaws.com:3306/demo?autoReconnect=True
    username: ${env.DB_USERNAME}
    password: ${env.DB_PASSWORD}

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  security:


    oauth2:
      client:
        registration:
          slack:
            client-id: ${env.CLIENT_ID}
            client-secret: ${env.CLIENT_SECRET}
            scope: openid, email

            redirect-uri: https://be.uplusbookhub.site/login/oauth2/code/slack

            #"{baseUrl}/{action}/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/slack)
            #client-name: Slack


        provider:
          slack:
            issuer-uri: https://slack.com
            authorization-uri: https://slack.com/openid/connect/authorize
            token-uri: https://slack.com/api/openid.connect.token
            user-info-uri: https://slack.com/api/openid.connect.userInfo

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


slack:
  user_token: ${env.USER_TOKEN}
  bot_token: ${env.BOT_TOKEN}
  bot_id : U03T792TDCK   #bamboo_id


app:
  cors:
    allowedOrigins: https://localhost:5000, , http://localhost:5000 , https://service.uplusbookhub.site , https://be.uplusbookhub.site
### Logging Level
logging:
  level:
    com.bns.bookhubservice: DEBUG
    org:
      hibernate:
        SQL: DEBUG



